name: flutter_html_video
description: This extension package allows the <video> tag to be rendered using the flutter_html package
version: 3.0.0-alpha.5
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.4 <2.0.0'
#  flutter_html: ^3.0.0-alpha.6
  flutter_html:
    path: ../..

  video_player: '>=2.8.2 <4.0.0'
  chewie: '>=1.7.5 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
